### ISSUE TITLE
Investigate this

### ISSUE THREAD

**Issue by fawkesley** [GreenDragonSoft/refundmytrain-django#20]
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/management/commands/cron_update_data.py", line 47, in handle
    handle(host, username, password)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/management/commands/cron_update_data.py", line 55, in handle
    download_latest(ftp)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/management/commands/cron_update_data.py", line 82, in download_latest
    load_push_port_file(filename, fobj)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/management/commands/cron_update_data.py", line 165, in load_push_port_file
    import_push_port_messages(f)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/importers/import_push_port_messages.py", line 72, in import_push_port_messages
    load_journies_from_xml_file(xml_fragment)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/importers/import_push_port_messages.py", line 88, in load_journies_from_xml_file
    handle_train_status(element)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/importers/import_push_port_messages.py", line 134, in handle_train_status
    handle_train_status_location(sub, journey)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/importers/import_push_port_messages.py", line 160, in handle_train_status_location
    timetable_arrival_time
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/importers/import_push_port_messages.py", line 216, in record_actual_arrival
    return a.minutes_late()
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/models.py", line 244, in minutes_late
    self.timetabled_calling_point.timetable_arrival_time)
  File "/home/vagrant/app/refundmytrain/apps/darwinpushport/models.py", line 124, in time_to_datetime
    assert isinstance(time, datetime.time)
AssertionError
```

**Comment by fawkesley** [comment]
[pPortData.log.2016-04-15-04-52.zip](https://github.com/GreenDragonSoft/refundmytrain-django/files/221275/pPortData.log.2016-04-15-04-52.zip)
^^ this file seems tocause it
